language: node_js

node_js:
    - stable
    
env:
  global:
    - CC_TEST_REPORTER_ID=

before_script:
  - chmod 0755 ./node_modules/.bin/mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - npm install

script:
  - npm run test:dev
  
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT